### PR TITLE
Styles/spacing

### PR DESCRIPTION
**Pull request by davidhunter08**
Created a page for spacing in styles.

### CODE REVIEW

**Comment by AdamChrimes** [comment]
@davidhunter08 please could you pop something in the CHANGELOG for this? I think this would be a new feature so the version number would be `1.4.0`

**Comment by AdamChrimes** [comment]
The build is failing because of linting the `design-example-overrides.scss` file.

```
app/styles/design-example-overrides.scss
  33:15  error  Hexadecimal colors should not be used                                          no-color-hex
  33:15  error  Color literals such as '#80afdc' should only be used in variable declarations  no-color-literals
  37:15  error  Hexadecimal colors should not be used                                          no-color-hex
  37:15  error  Color literals such as '#337ec6' should only be used in variable declarations  no-color-literals

✖ 4 problems (4 errors, 0 warnings)
```

**Comment by AdamChrimes** [comment]
Ready for review by @sarawilcox

**Comment by ericlamarca** [comment]
@AdamChrimes added the content tweaks - you okay to review / merge?

**Pull request merged**
