### PR TITLE
Add release steps

### PR DESCRIPTION
**Pull request by DomBaker**
## Description

Release steps added into the README so that the release process is documented publically.

You can view the documentation here: https://github.com/nhsuk/nhsuk-service-manual/blob/DomBaker-patch-1/README.md#creating-a-tagged-released

### CODE REVIEW

**Review by chrimesdev — APPROVED** [review]

**Comment by sarawilcox** [comment]
Hi @chrimesdev and @DomBaker, just checking we're not releasing this yet. I haven't had a chance to review Dom's changes.

**Comment by chrimesdev** [comment]
Hi @sarawilcox this is just documentation in the GitHub repository `README` file, it doesn't affect the service manual website and no release is required. 

We can iterate these release steps any time in the future (after people have followed them to do releases), but for the time being we need some kind of documentation for the release process so that we aren't blocked by only certain members of the team knowing the steps.

**Comment by sarawilcox** [comment]
OK @chrimesdev, thanks. Would you mind leaving the ticket in the review column, please? I do want to have another look at it and we can then test it with team members when we do a release.

**Comment by sarawilcox** [comment]
I've made a few minor text changes. All done.

**Pull request merged**
