### PR TITLE
Update page template descriptions

### PR DESCRIPTION
**Pull request by frankieroberto**
⚠️ **Do not merge and deploy until the breaking change release of NHS.UK Frontend has been released** ⚠️ 

## Description

This updates the way that the [page template](https://service-manual.nhs.uk/design-system/styles/page-template) is set up. 

Previously there were 2 blocks defined: `outerContent` and `beforeContent`, with the former recommended for back links and the latter for breadcrumbs.

This merges the two blocks together as one named `beforeContent` which is placed within the `<div class="nhsuk-width-container">` but before the `<main>` element.

This is recommended for both breadcrumbs and back links - and any other components which should appear within the width of the page, but before the main element.

These components are:

* skipped when using the "skip to main content" link
* not included when printing the page
* generally not shown when using "reader mode" in browsers (although this varies by browser)

In addition, the margins on the back links are no longer specified, as the back link now has margin above it by default.

| Before | After |
|----|-----|
| Screenshot of page template before, showing both a beforeContent and outerContent block | Screenshot of page template after, showing only a beforeContent block |

This change aligns the page template block naming conventions with the [GOV.UK Design System page template](https://design-system.service.gov.uk/styles/page-template/).

Note: in both, the `main` block is confusingly named as that block appears outside of both the `<main>` tag and the `beforeContent` block, rather than being within the `<main>` tag.

### Related issue

* See [Back link and breadcrumb changes](https://github.com/nhsuk/nhsuk-frontend/pull/1002) in NHS.UK Frontend

## Checklist

- [ ] Tested against the [NHS.UK frontend testing policy](https://github.com/nhsuk/nhsuk-frontend/blob/main/docs/contributing/testing.md) (Resolution, Browser & Accessibility)
- [ ] Code follows the [NHS.UK frontend coding standards](https://github.com/nhsuk/nhsuk-frontend/blob/main/docs/contributing/coding-standards.md)
- [ ] Version number has been increased in `package.json` (using [SEMVER](https://semver.org/))
- [ ] CHANGELOG entry
- [ ] [Whats new page](https://service-manual.nhs.uk/whats-new) entry

### CODE REVIEW

**Review by edwardhorsford — COMMENTED** [review]
Looking good so far - will you be adding content for the changelog to cover this breaking change? I imagine it could end up affecting a lot of templates.

**Comment by frankieroberto** [comment]
> Looking good so far - will you be adding content for the changelog to cover this breaking change? I imagine it could end up affecting a lot of templates.

Do you mean the changelog for nhsuk-frontend? I’ve not mentioned it there, as the frontend package doesn’t actually contain the template at all (unlike the govuk one).

We should definitely describe the changes in the [What’s new page](https://service-manual.nhs.uk/whats-new) in the service manual though. Will do that in a separate PR!

**Comment by anandamaryon1** [comment]
@frankieroberto Thanks for this, I'd done some of this already on this branch: https://github.com/nhsuk/nhsuk-service-manual/compare/main...review/1-release-7-0-0, so I've merged this work into work that branch. I've also updated the whats new and changelog on that branch.

**Comment by frankieroberto** [comment]
@anandamaryon1 ah thanks! shall I close this PR now in favour of #2035?

**Comment by anandamaryon1** [comment]
@frankieroberto I'll come back and tidy once the release is out

**Comment by anandamaryon1** [comment]
Released as part of v7.0.0: https://github.com/nhsuk/nhsuk-service-manual/pull/2040

**Pull request closed without merging**
