### PR TITLE
added gitpod documentation to README

### LINKED ISSUE #1353: Add Gitpod to service manual
Adding Gitpod to the service manual allows for people to access a development like environment without the need for any prerequisites and is fully browser-based.

Information on Gitpod can be found here: https://www.gitpod.io/docs/

- [x] Add Gitpod yml script
- [x] Add button to README
- [x] add pre-build 
- [x] check Gitpod for correct config
- [x] Add documentation to README on Gitpod (to be discussed with @sarawilcox)

### PR DESCRIPTION
**Pull request by DomBaker**
## Description

Added some documentation, keeping it simple and concise - requires content approval. fixes #1353
## Checklist

- [ ] Tested against the [NHS.UK frontend testing policy](https://github.com/nhsuk/nhsuk-frontend/blob/master/docs/contributing/testing.md) (Resolution, Browser & Accessibility)
- [ ] Code follows the [NHS.UK frontend coding standards](https://github.com/nhsuk/nhsuk-frontend/blob/master/docs/contributing/coding-standards.md)
- [ ] Version number has been increased in `package.json` (using [SEMVER](https://semver.org/))
- [ ] CHANGELOG entry
- [ ] [Whats new page](https://service-manual.nhs.uk/whats-new) entry
- [ ] Page updated date

### CODE REVIEW

**Comment by karlgoldstraw** [comment]
@DomBaker please can you add an ALT tag to the images on the readme 
https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#images

**Comment by DomBaker** [comment]
Hi @karlgoldstraw - This is already done by default although you can't see it in the README. 
Below is the inspection of the page: 
Screenshot 2021-08-05 at 12 16 01
Below is the Screen Reader output:
Screenshot 2021-08-05 at 12 20 44

**Comment by karlgoldstraw** [comment]
Ah cool! Cheers @DomBaker

**Comment by chrimesdev** [comment]
Review and merge this one

**Comment by EllenDoyle** [comment]
Sara and Dom agreed to prioritise in Sprint 30.

**Review by sarawilcox — APPROVED** [review]

**Pull request merged**
