### PR TITLE
Component variations and fixes

### PR DESCRIPTION
**Pull request by ericlamarca**
Work in progress

### CODE REVIEW

**Comment by AdamChrimes** [comment]
@ericlamarca is this branch still a work in progress or does it need closing?

**Comment by ericlamarca** [comment]
Hey @AdamChrimes - 242e9c7, e6a01e9, 6194a96, 8e5d4f8 all need to be merged. But a472166 and 
dfb195c are not relevant anymore. What would you recommend we do?

**Comment by AdamChrimes** [comment]
@ericlamarca I've reverted those 2 commits so they should be undone now. Would you be able to have a quick look locally and see if you're happy? You may need to pull down the latest changes (reverts) with `git pull origin components`.

**Comment by ericlamarca** [comment]
Thanks @AdamChrimes - looking good 👍

**Comment by AdamChrimes** [comment]
Thanks @ericlamarca should appear on staging soon.

**Pull request merged**
