### PR TITLE
Amended content on sex and intersex

### PR DESCRIPTION
**Pull request by JackMatthams**

### CODE REVIEW

**Comment by AdamChrimes** [comment]
Hey @JackMatthams please could you add a entry to the `CHANGELOG.md` file under 3.0.4 and does this need an entry on the 'Whats new' pages?

**Comment by AdamChrimes** [comment]
Also in command line if you type `git config --global user.email "email@example.com"` (replacing email@example.com with your GitHub email) this will associate commits to your GitHub account.

**Comment by JackMatthams** [comment]
@AdamChrimes I'll add the changelog entry. It will probably need to be added to what's new but we'll wait and see today if there are any further changes from Sara to make to it before doing that. I've tried the GitHub account line again - I tried it before, hopefully it works this time.

**Comment by sarawilcox** [comment]
@JackMatthams and @AdamChrimes - approved. I'll give it a final check through once it's on master but am fine with merging and updating What's new.

**Pull request merged**
