### PR TITLE
Define inclusion and accessibility

### PR DESCRIPTION
**Pull request by sarawilcox**
## Description
Add info about inclusion and accessibility to service standard 5

## Checklist

- [ ] Tested against the [NHS.UK frontend testing policy](https://github.com/nhsuk/nhsuk-frontend/blob/master/docs/contributing/testing.md) (Resolution, Browser & Accessibility)
- [ ] Code follows the [NHS.UK frontend coding standards](https://github.com/nhsuk/nhsuk-frontend/blob/master/docs/contributing/coding-standards.md)
- [ ] Version number has been increased in `package.json` (using [SEMVER](https://semver.org/))
- [ ] CHANGELOG entry - not yet- I'll do this before we release
- [x] [Whats new page](https://service-manual.nhs.uk/whats-new) entry
- [x] Page updated date

### CODE REVIEW

**Comment by sarawilcox** [comment]
Hi, could we merge this with master now, please?
Once it's on staging, I'll share it with the team. 
Also I need to ask a content designer to double-check my work over the next couple of days.
We should be able to release it next Tuesday. 

@karlgoldstraw, I've marked this for you to approve. (And copied Dave in, but I don't think Dave needs to see it.) Please let me know if you have any questions.

**Review by karlgoldstraw — COMMENTED** [review]
Hi Sara,

The only thing I'd question here is the use of d/Deaf. 

> ...like people who are Deaf

[should this be 'deaf'?](https://www.ai-media.tv/the-difference-between-d-deaf-and-hard-of-hearing-2/)

**Comment by sarawilcox** [comment]
Hi @karlgoldstraw, it's something we've debated as content designers and taken advice on from Deaf people. See the entry in the content style guide: https://service-manual.nhs.uk/content/a-to-z-of-nhs-health-writing#Deaf-people

**Comment by sarawilcox** [comment]
Do ask questions like that though.

**Comment by karlgoldstraw** [comment]
Thanks Sara!

**Comment by sarawilcox** [comment]
Hi @karlgoldstraw, if you get a mo, could you approve this please?

**Review by karlgoldstraw — APPROVED** [review]
All looks fine :)

**Pull request merged**
