### PR TITLE
Update PDFs page and amend links across site

### PR DESCRIPTION
**Pull request by sarawilcox**
## Description
Rename and update PDF file after January Style Council meeting. 
Update links across site with new file name and page title.

@markasrobinson , would you mind checking the content please?
@AdamChrimes , would you mind checking the code please, **esp the xml file**?

I haven't updated the What's new section or changelog yet. I'll do that once all files have been merged in.

### Related issue
[Amend PDFs page after January Style Council meeting #963](https://github.com/nhsuk/nhsuk-service-manual/issues/963)

## Checklist

- [ ] Tested against the [NHS.UK frontend testing policy](https://github.com/nhsuk/nhsuk-frontend/blob/master/docs/contributing/testing.md) (Resolution, Browser & Accessibility)
- [ ] Code follows the [NHS.UK frontend coding standards](https://github.com/nhsuk/nhsuk-frontend/blob/master/docs/contributing/coding-standards.md)
- [ ] Version number has been increased in `package.json` (using [SEMVER](https://semver.org/))
- [ ] CHANGELOG entry - not yet
- [ ] [Whats new page](https://service-manual.nhs.uk/whats-new) entry - not yet
- [x] Page updated date - on PDF page but not on other pages where I only updated links

### CODE REVIEW

**Review by markasrobinson — APPROVED** [review]
Fixed one typo in content and made links consistent across all files (capped down HTML to html).

**Comment by AdamChrimes** [comment]
Code looks good, do we want a redirect setting up from `/content/pdfs` to `/content/pdfs-and-other-non-html-documents` @sarawilcox?

**Comment by sarawilcox** [comment]
Hi @AdamChrimes, yes, please, if you wouldn't mind. Some comms teams may have bookmarked the old page.

**Review by AdamChrimes — APPROVED** [review]

**Comment by AdamChrimes** [comment]
Added redirect and approved the changes @sarawilcox just needs a CHANGELOG and Whats new entry

**Pull request merged**
