### PR TITLE
Change image in image component and explain captions

### PR DESCRIPTION
**Pull request by sarawilcox**
## Description
At Style Council, we agreed to bring the example image in the image component into line with the accessibility guidance example. Having 2 examples was confusing and the accessibility guidance example is the better one.

Also add more guidance about captions - agreed at Style Council

### Related issue
https://github.com/nhsuk/nhsuk-service-manual/issues/1231

## Checklist

- [ ] Tested against the [NHS.UK frontend testing policy](https://github.com/nhsuk/nhsuk-frontend/blob/master/docs/contributing/testing.md) (Resolution, Browser & Accessibility)
- [ ] Code follows the [NHS.UK frontend coding standards](https://github.com/nhsuk/nhsuk-frontend/blob/master/docs/contributing/coding-standards.md)
- [ ] Version number has been increased in `package.json` (using [SEMVER](https://semver.org/))
- [ ] CHANGELOG entry - not yet
- [ ] [Whats new page](https://service-manual.nhs.uk/whats-new) entry - not yet
- [x] Page updated date - done

### CODE REVIEW

**Comment by sarawilcox** [comment]
@davidhunter08 Would you mind checking this please? 

Also, we need to delete the image we currently use from the assets folder: https://assets.nhs.uk/prod/images/S_1017_allergic-conjunctivitis_M15.2e16d0ba.fill-320x213.jpg. Can you help with that, please?

**Comment by chrimesdev** [comment]
@sarawilcox that image lives on nhs.uk Wagtail assets (uploaded through the CMS admin) so its not something we have in our service manual code base

**Comment by sarawilcox** [comment]
Thanks @chrimesdev. What do we have to do to get it changed?

**Comment by chrimesdev** [comment]
Theres nothing we need to do in our code base, as we're now using the new image path (https://assets.nhs.uk/prod/images/S_0318_Bullous_pemphigoid_lesions_.2e16d0ba.fill-320x213.jpg). 

That image can stay on the nhs.uk assets as its probably used by some Wagtail places (or possibly somewhere else)

**Comment by sarawilcox** [comment]
@chrimesdev, sorry - yes, I've just realised that. It is still used in Wagtail. We just won't refer to it.

**Review by davidhunter08 — APPROVED** [review]
LGTM

**Comment by davidhunter08** [comment]
Looks like we just need the CHANGELOG entry + what's new page entry @sarawilcox, then we're good to go.

**Pull request merged**
